import PartModal from '@/components/PartModal.vue'
import { key } from '@/store'
import { Actions } from '@/store/type-actions'
import { mount } from '@vue/test-utils'
import { createStore } from 'vuex'
