export enum Mutations {
    NOTIFY = 'NOTIFY',

    ADD_USER = 'ADD_USER',
    LOGIN_USER = 'LOGIN_USER',
    USER_LOGGED = 'USER_LOGGED',

    ADD_FILTERS = 'ADD_FILTERS',
    ADD_CONFIGURED_FILTERS = 'ADD_CONFIGURED_FILTERS',
    ADD_FEEDBACKS = 'ADD_FEEDBACKS',

    TOOGLE_LOADING = 'TOOGLE_LOADING',
}
